version: "3"
services:
  contract:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    ports: 
      - "4000:3000"
    networks:
      - "devnet"
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports: 
      - "4001:3000"
    networks:
      - "devnet"
networks:
  devnet: